networks:
  toubilib.net:
    driver: bridge

services:

  # service gateway
  gateway.toubilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - "7080:80"
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - api.toubilib
    env_file: ./app/config/.env
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"
    
  # service api.toubilib : api pour la prise de rdv
  api.toubilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
      - toubiauth.db
      - toubirdv.db
      - toubipat.db
    env_file: ./app/config/.env
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # service microservice praticiens
  api.praticiens:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6081:80'
    volumes:
      - ./app-praticiens:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
    env_file: ./app/config/.env
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # service microservice rendez-vous
  api.rdv:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6082:80'
    volumes:
      - ./app-rdv:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubirdv.db
      - api.praticiens
    env_file: ./app/config/.env
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # service microservice authentification
  api.auth:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6083:80'
    volumes:
      - ./app-auth:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiauth.db
    env_file: ./app/config/.env
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  toubiprati.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${PRAT_USERNAME:-toubiprat}
      POSTGRES_PASSWORD: ${PRAT_PASSWORD:-toubiprat}
      POSTGRES_DB: ${PRAT_DATABASE:-toubiprat}
    ports:
      - '5432:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  toubiauth.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${AUTH_USERNAME:-toubiauth}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD:-toubiauth}
      POSTGRES_DB: ${AUTH_DATABASE:-toubiauth}
    ports:
      - '5433:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  toubirdv.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${RDV_USERNAME:-toubirdv}
      POSTGRES_PASSWORD: ${RDV_PASSWORD:-toubirdv}
      POSTGRES_DB: ${RDV_DATABASE:-toubirdv}
    ports:
      - '5434:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  toubipat.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${PAT_USERNAME:-toubipat}
      POSTGRES_PASSWORD: ${PAT_PASSWORD:-toubipat}
      POSTGRES_DB: ${PAT_DATABASE:-toubipat}
    ports:
      - '5435:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - toubilib.net
